//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageSlips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentClient
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
    }
}
