//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageSlips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSlip
    {
        public int mID { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string categories { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string phoneNum { get; set; }
        public string message { get; set; }
        public string location { get; set; }
        public string other { get; set; }
        public string userName { get; set; }
    
        public virtual User User { get; set; }
    }
}
